name: Publish

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "Export/html5/bin"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haxe environment
        # You may pin to the exact commit or the version.
        # uses: krdlab/setup-haxe@3437f1adfca98b22815d926271cc39faaf996f25
        uses: krdlab/setup-haxe@v1.5.1
        with:
          # Version Spec of the version to use. Example: 4.3.1
          haxe-version: 4.3.4 # default is 4.3.1
          # Used to specify the path to a dependency file.
          cache-dependency-path: 'libs.hxml' # optional

      - run: haxelib install libs.hxml --always --quiet
      - run: haxelib run openfl setup
      - run: haxelib run openfl build html5
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    
